### ISSUE TITLE
HiveMind: First Steps

### ISSUE THREAD

**Issue by BradenEverson** [BradenEverson/driem#1]
The HiveMind interface will be a web server that accepts connections via websocket. The agent will connect to the HiveMind and stream it's binary and serialized session to it accordingly. For these first steps, whoever would like to should do the following:

- Set up a basic web server in Rust that listens on 0.0.0.0:1940
- Accept websocket connections
    - For every websocket connection, await asynchronously for new messages
    - If text, it's the serialized json string of the agent's session
    - If binary and we already have an agent session, stream the bytes to the Agent's data
- Create a struct `AgentSessionWithContext` that holds an AgentSession and some flag `NeedsTraining` or something like that.

First Steps: Salvin will finish learning Rust the week of the 16th. 
Next week: Websocket implementation

**Comment by BradenEverson** [comment]
My code in https://github.com/BradenEverson/td/blob/main/src/main.rs shows how to get running with an async webserver

https://blog.guillaume-gomez.fr/articles/2017-02-22+Rust+asynchronous+HTTP+server+with+tokio+and+hyper
https://medium.com/@ajay.bhatia/creating-a-basic-http-server-in-rust-using-hyper-a-step-by-step-tutorial-459b48d61151

**Comment by chowdhuryj-github** [comment]
okay!

**Comment by BradenEverson** [comment]
DUE: 9/27/24

**Comment by chowdhuryj-github** [comment]
**Update 1:** submitted my first commit to the repository on the "salvin-branch" branch. Completed the following:

1. **Section 20.1:**  Building a Single-Threaded Web Server

**Comment by chowdhuryj-github** [comment]
**Update 2:** submitted a second commit. Almost have the multi-threaded web server done. Complete implementation should be done by tomorrow.
