### ISSUE TITLE
Joint creation UI

### ISSUE THREAD

**Issue by BradenEverson** [BradenEverson/driem#4]
The way that I currently have things set up for body orientation uses a `Slotmap<PeripheralNode>`, meaning that we can encode context into our body orientation by showing what motors are connected to what, or what sensors are connected to specific motors. This also allows disjoint sensors to exist, and if need be we can flatten the Slotmap entirely for ease of use early on.

That being said, I think it could be cool to have a small web GUI written up that allows users to create Nodes and connect them with each other. They could then serialize this to Json and load it as the model's body in the jetson software

Something like a UI that would allow developers to make this:
![image](https://github.com/user-attachments/assets/3a76ea2a-d7fa-44b7-85e6-cc2ed12418cc)

**Comment by chowdhuryj-github** [comment]
I'll take it.

**Comment by BradenEverson** [comment]
We no longer need this as the joints will be inferred from the URDF file generated by solidworks
